# Assignment 1 - CIC-1205

## Exercise 2 - Diamond price prediction

Student: Balthazar Paixão


## Code


In [1]:
import numpy as np
import pandas as pd

In [3]:
df_diamonds = pd.read_csv("../class-repo/cic1205/data/diamonds.csv")

In [4]:
df_diamonds.sample(3)

Unnamed: 0  carat    cut color clarity  depth  table  price     x  \
52716       52717   0.56  Ideal     F    VVS2   61.3   57.0   2554  5.31   
21144       21145   1.51   Good     F     SI2   63.4   57.0   9301  7.25   
12925       12926   1.01   Good     F     SI1   62.4   59.0   5378  6.29   

          y     z  
52716  5.35  3.26  
21144  7.29  4.61  
12925  6.33  3.94

In [5]:
df_diamonds = df_diamonds.drop(columns=["Unnamed: 0"])

In [6]:
colnames = [column for column in df_diamonds.columns]
colnames

['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y', 'z']

## Pré-processamento dos dados


Esta etapa é muito importante, uma má execução desta etapa pode causar problemas no treino.

Aqui, verificamos os valores presentes em colunas que sabemos que se tratam de dados categóricos. Então é necessário pensar se estes dados são _nominais_ (valor que indica categoria, sem levar em consideração um "ranking") ou _ordinais_ (valor que indica categoria, mas que carrega uma relação de ordem com demais valores presentes).

Podemos ver que os dados são ordinais. Podemos ver que há valores para os quais vai haver um corte, cor ou claridade do diamante que vai ser ideal ou não, então isso é modelado na codificação.


In [7]:
print(df_diamonds["cut"].unique())
print(df_diamonds["color"].unique())
print(df_diamonds["clarity"].unique())

['Ideal' 'Premium' 'Good' 'Very Good' 'Fair']
['E' 'I' 'J' 'H' 'F' 'G' 'D']
['SI2' 'SI1' 'VS1' 'VS2' 'VVS2' 'VVS1' 'I1' 'IF']


In [8]:
df_diamonds["cut"].replace(
    {"Fair": 1, "Good": 2, "Very Good": 3, "Premium": 4, "Ideal": 5}, inplace=True
)
df_diamonds["color"].replace(
    {"J": 1, "I": 2, "H": 3, "G": 4, "F": 5, "E": 6, "D": 7}, inplace=True
)
df_diamonds["clarity"].replace(
    {"I1": 1, "SI2": 2, "SI1": 3, "VS2": 4,
        "VS1": 5, "VVS2": 6, "VVS1": 7, "IF": 8},
    inplace=True,
)

In [11]:
print(df_diamonds["cut"].unique())
print(df_diamonds["color"].unique())
print(df_diamonds["clarity"].unique())

[5 4 2 3 1]
[6 2 1 3 5 4 7]
[2 3 5 4 6 7 1 8]


In [12]:
df_diamonds.sample(3)

carat  cut  color  clarity  depth  table  price     x     y     z
7084    0.90    2      6        3   63.1   61.0   4165  6.14  6.18  3.89
35364   0.38    4      3        4   60.6   58.0    898  4.70  4.68  2.84
29002   0.34    4      5        4   62.6   59.0    686  4.44  4.48  2.79

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [16]:
# Divisão entre treino e teste
X = df_diamonds.drop(columns=['price'])
y = df_diamonds['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#### Normalização das features
É importante normalizarmos as features para equilibrar as suas ordens de grandeza, para os mesmos serem processados na etapa de treino. Isso é feito porque a existência de discrepâncias entres essas orders de grandeza prejudica o ajuste dos modelos em alguns algoritmo de aprendizado.

É também importante entender que o ajuste do *scaler* deve ser feito apenas sobre o conjunto de treino,
para evitar que haja vazamento de dados (fenômeno conhecido como [data leakage](https://en.wikipedia.org/wiki/Leakage_(machine_learning)).

In [17]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(43152, 9)
(43152,)
(10788, 9)
(10788,)


## Treinamento do modelo

In [21]:
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_val_score


In [20]:
LR = LinearRegression()
LR.fit(X_train, y_train)

LS = Lasso()
LS.fit(X_train, y_train)

DT = DecisionTreeRegressor()
DT.fit(X_train, y_train)

RF = RandomForestRegressor()
RF.fit(X_train, y_train)

KNN = KNeighborsRegressor()
KNN.fit(X_train, y_train)

GB = GradientBoostingRegressor()
GB.fit(X_train, y_train)

GradientBoostingRegressor()

In [ ]:
#Como métricas de avaliação, use o MSE e o coeficiente de determinação R2.

In [27]:
#Linear Regression


cv_score = cross_val_score(LR, X_test, y_test, scoring="neg_mean_squared_error")
print(f"LinearRegressionRegressor: {(-1 * cv_score.mean())}")

LinearRegressionRegressor: 1425706.8732972168


In [29]:
cv_score = cross_val_score(LS, X_test, y_test, scoring="neg_mean_squared_error")
print(f"LassoRegressor: {(-1 * cv_score.mean())}")

/home/balthapaixao/Desktop/baltha/projects/portfolio/.venv/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.115e+08, tolerance: 1.411e+07
  model = cd_fast.enet_coordinate_descent(
/home/balthapaixao/Desktop/baltha/projects/portfolio/.venv/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.484e+08, tolerance: 1.396e+07
  model = cd_fast.enet_coordinate_descent(
/home/balthapaixao/Desktop/baltha/projects/portfolio/.venv/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to inc

LassoRegressor: 1427423.827822154


/home/balthapaixao/Desktop/baltha/projects/portfolio/.venv/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.767e+08, tolerance: 1.392e+07
  model = cd_fast.enet_coordinate_descent(


In [32]:
cv_score = cross_val_score(DT, X_test, y_test, scoring="neg_mean_squared_error")
print(f"Decision Tree Regressor: {(-1 * cv_score.mean())}")

Decision Tree Regressor: 723534.9781257265


In [33]:
cv_score = cross_val_score(RF, X_test, y_test, scoring="neg_mean_squared_error")
print(f"Random Forest Regressor: {(-1 * cv_score.mean())}")

Random Forest Regressor: 365966.5138765785


In [35]:
cv_score = cross_val_score(KNN, X_test, y_test, scoring="neg_mean_squared_error")
print(f"K Nearest Neighbors Regressor: {(-1 * cv_score.mean())}")

K Nearest Neighbors Regressor: 694351.4799407648


In [36]:
cv_score = cross_val_score(GB, X_test, y_test, scoring="neg_mean_squared_error")
print(f"Gradient Boosting Regressor: {(-1 * cv_score.mean())}")

Gradient Boosting Regressor: 402629.3334239013
